# Generated by Django 4.0.2 on 2022-07-31 15:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutindex_aboutpage_formpage_servicepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='fact',
            field=wagtail.core.fields.StreamField([('fact', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(page_type=['home.ServicePage'], required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Read More', max_length=40, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='work',
            field=wagtail.core.fields.StreamField([('work', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=40, required=False)), ('text', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], required=False))]))), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceindex',
            name='service_main',
            field=wagtail.core.fields.StreamField([('service_main', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(page_type=['home.ServicePage'], required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Read More', max_length=40, required=False))]))], blank=True, null=True),
        ),
    ]
