# Generated by Django 4.0.2 on 2022-08-04 18:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_main_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimony',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='work',
        ),
        migrations.RemoveField(
            model_name='serviceindex',
            name='client',
        ),
        migrations.RemoveField(
            model_name='serviceindex',
            name='service_main',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_list',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_testimony',
        ),
        migrations.AlterField(
            model_name='serviceindex',
            name='service_page',
            field=wagtail.core.fields.StreamField([('service_list', wagtail.core.blocks.StructBlock([('jumbotron_color', wagtail.core.blocks.CharBlock(help_text='Enter a hexdecimal color for the background e.g #000000', max_length=40, required=False)), ('service_index', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image_icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=False))])))])), ('client', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=60, required=False))])), ('service_main', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('second_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(page_type=['home.ServicePage'], required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Read More', max_length=40, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service_contact',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(max_length=60, required=False))])), ('service_contact', wagtail.core.blocks.StructBlock([('contact_link', wagtail.core.blocks.PageChooserBlock(page_type=['home.FormPage'], required=False)), ('text', wagtail.core.blocks.CharBlock(default='Lets talk', max_length=60, required=False))])), ('faq', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(required=True)), ('answer', wagtail.core.blocks.CharBlock(max_length=60, required=True))])), ('service_testimony', wagtail.core.blocks.StructBlock([('jumbotron_color', wagtail.core.blocks.CharBlock(default='#000000', help_text='Enter a hexdecimal color for the background e.g #000000', max_length=40, required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False)), ('service_testimony', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=40, required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False))])))])), ('service_list', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Our Services', max_length=60, required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False)), ('list_item', wagtail.core.blocks.CharBlock(max_length=40, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
